import {forwardRef} from "react";
import {useGLTF} from "@react-three/drei";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: akshatmittal (https://sketchfab.com/akshatmittal)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/2021-macbook-pro-14-m1-pro-m1-max-f6b0b940fb6a4286b18a674ef32af2d3
title: 2021 Macbook Pro 14" (M1 Pro / M1 Max)
*/

const defaultLidRotation = Math.PI; // start with laptop lid closed

const MacBook3DModel = forwardRef(({texture, children, ...props}, ref) => {
    const {nodes, materials} = useGLTF("/mbp-v1-pipe.glb");
    const {macbook: macbookRef, lid: lidRef} = ref;

    return (
        <group {...props} dispose={null} ref={macbookRef}>
            <group ref={lidRef} position={[0, -0.43, -11.35]} rotation={[defaultLidRotation, 0, 0]}>
                <mesh geometry={nodes.back_1.geometry} material={materials.blackmatte} />
                <mesh receiveShadow castShadow geometry={nodes.back_2.geometry} material={materials.aluminium} />
                <mesh geometry={nodes.matte.geometry}>
                    <meshLambertMaterial map={texture} toneMapped={false} />
                </mesh>
            </group>
            {children}
            <mesh
                geometry={nodes.body_1.geometry}
                material={materials.aluminium}
                material-color="#aaaaaf"
                material-envMapIntensity={0.2}
            />
            <mesh geometry={nodes.body_2.geometry} material={materials.blackmatte} />
        </group>
    );
});

export default MacBook3DModel;
